### ISSUE TITLE
[enhance] better sphinx theme?

### ISSUE THREAD

**Issue by the872** [glm-tools/pyglmnet#103]
Probably not something for [version 0.1](https://github.com/pavanramkumar/pyglmnet/milestones/version%200.1)  but found [this bootstrap theme](https://github.com/ryan-roemer/sphinx-bootstrap-theme) [(demo)](http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html) that I think looks better than the current theme.

edit: maybe even do a [gitbook](http://toolchain.gitbook.com)

**Comment by pavanramkumar** [comment]
thanks @the872 yes, we can work on css/theme issues for later versions.

**Comment by jasmainak** [comment]
yeah we can do that. One attractive feature of the `readthedocs` template is that you can host your documentation on their website, but since we are already doing it on `github`, we can experiment with themes :)

**Comment by jasmainak** [comment]
let's close this?

**Comment by jasmainak** [comment]
Closing as the issue is not active for more than a year
