### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#106]
Documentation and examples can use some more clarity and polishing. I can work on this to provide a basic structure tomorrow. Feel free to follow up!

**[Tutorial](http://pavanramkumar.github.io/pyglmnet/auto_examples/plot_glmnet.html)**
- ~~Tutorial needs to be moved out of examples gallery and added as a separate section in documentation~~
- Expand on construction of GLMs for exponential families
- Add pseudo-code in the form of an algorithm table
- ~~Provide reference math for likelihood function, gradients, hessians~~ [see cheatsheet]

**Examples**
~~Need to be organized into three separate categories:~~
- ~~API demo~~
- ~~Benchmarks (comparisons with scikit learn and R)~~ [see `benchmarks.py` and README]
- ~~Applications to real data~~ [see examples]

**Comment by jasmainak** [comment]
for benchmarks you might want to look at this: https://github.com/scikit-learn/ml-benchmarks

**Comment by jasmainak** [comment]
can we close this issue? we should start pushing for a 0.1 release soon

**Comment by pavanramkumar** [comment]
The benchmarks are still incomplete. I've been working on a comparison with R. Let's keep this issue open as a general docs checklist for the 0.1 release

**Comment by themantalope** [comment]
What is the state of this issue? Have bullet points 2 and 3 in the first comment been addressed?

**Comment by pavanramkumar** [comment]
Working on those issues now
