### ISSUE TITLE
add dependencies to Developer Documentation

### ISSUE THREAD

**Issue by the872** [glm-tools/pyglmnet#113]
[referring to this](http://pavanramkumar.github.io/pyglmnet/developers.html), you have to install a couple extra thing to do make html on sphinx

➜  ~ pip install sphinx 
➜  ~ pip install sphinx-gallery 
➜  ~ pip install Image
➜  ~ pip install matplotlib    

its not too hard to deduce with the error messages you get back from terminal but it could be helpful to have in the docs

**Comment by jasmainak** [comment]
why do you need `Image` ?

**Comment by the872** [comment]
does it generate the image of the graphs?

**Comment by marquesVF** [comment]
At #115 it's possible to solve those dependencies with one command. It also would be helpful to have in the docs.

**Comment by jasmainak** [comment]
feel free to add the dependencies to the developer docs after addressing the comments in #115.

**Comment by jasmainak** [comment]
This is taken care of. Closing
