### ISSUE TITLE
Add progress bar for estimation using tqdm

### ISSUE THREAD

**Issue by hugoguh** [glm-tools/pyglmnet#135]
```
>> pip install tqdm
```

``` python
from tqdm import tqdm
for iter in tqdm(range(maxiter)):
    # do stuff
```

**Comment by jasmainak** [comment]
I've never used `tqdm` but we used `Progressbar` in the past. The problem with that is that the logger does not go well with these tools as you can't control the verbosity here.

**Comment by jasmainak** [comment]
closing issue. @hugoguh feel free to reopen if it's still relevant for you
