### ISSUE TITLE
estimator check

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#153]
I was looking at `scikit-learn-contrib` for the future and came across a helpful test for whether our estimator passes `scikit-learn`'s standards for what should be an estimator. 

http://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.check_estimator.html

It seems like we need to write `set_params()` method.

**Comment by pavanramkumar** [comment]
related to #157 and #158

**Comment by jasmainak** [comment]
We agreed we are not going down this path in https://github.com/glm-tools/pyglmnet/pull/190. Closing the issue.
