### ISSUE TITLE
demonstrate group lasso with example

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#154]
http://genes.mit.edu/burgelab/maxent/ssdata/MEMset/

**Comment by jasmainak** [comment]
also tikhonov maybe?

**Comment by themantalope** [comment]
What exactly is the task in this case? I'm not familiar with this dataset, do you know if there is a paper associated with the data?

**Comment by pavanramkumar** [comment]
@themantalope Section 5 in this paper describes the data: ftp://ftp.stat.math.ethz.ch/Manuscripts/buhlmann/lukas-sara-peter.pdf

The task is to apply `pyglmnet`'s group lasso feature to this dataset as an illustrative example. see example docs here: http://pavanramkumar.github.io/pyglmnet/auto_examples/index.html

**Comment by pavanramkumar** [comment]
@themantalope is working on this
