### ISSUE TITLE
add zenodo

### ISSUE THREAD

**Issue by jasmainak** [glm-tools/pyglmnet#162]
Here is how to get zenodo to work: https://guides.github.com/activities/citable-code/

For whoever is bored :)

**Comment by pavanramkumar** [comment]
I want to try to submit here: http://joss.theoj.org/ after the 0.1 release. Seems like a new community worth supporting. They peer review your code and you get a DOI which is indexed by google scholar

**Comment by jasmainak** [comment]
You get a DOI with zenodo as well. The benefit of zenodo is that you get a new DOI with every release (I think), so basically new contributors also get credit. This is one of the biggest problems of publishing software -- how to give credit once you have already published the work. Numpy paper has 3 authors but clearly many more people have contributed to making it a successful project.

I don't really know much about the pros and cons of different journals. Here is a complete list: https://www.software.ac.uk/resources/guides/which-journals-should-i-publish-my-software

I saw a discussion on the nipy mailing list about JORS recently: http://openresearchsoftware.metajnl.com/

**Comment by pavanramkumar** [comment]
closed by 070051b913b07c8839c14e4071e2054953989148
