### ISSUE TITLE
transfer ownership to glm-tools organization

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#166]
There are several long term advantages to moving this repo out of my personal account, into an organization. I think it's good to do this before the first release, so that users are not confused in the future. 

If not, I will transfer it to a new github organization called `glm-tools`. As a consequence: 
- the repo's new home will be at `http://github.com/glm-tools/pyglmnet`. 
- the `gh-pages` associated will still not change until I find a new way to host it under the github organization.
- all your forks, as well as issues, watchers, stars will be preserved.

If there are any negative consequences, do chime in. If no objections, I will transfer by Oct 21.
If no objections, there is no need to reply.

@jasmainak @daniel-acuna @titipata @hugoguh @marquesVF @themantalope

**Comment by daniel-acuna** [comment]
I think it would take credit out of your effort and i think you need it for this job season at least. do it next sem.

**Comment by jasmainak** [comment]
+1 from my end. I agree completely

**Comment by themantalope** [comment]
Sounds like a good idea.

@daniel-acuna if @pavanramkumar ends up submitting the library to a journal for review, wouldn't that be just as effective if not more?

**Comment by daniel-acuna** [comment]
Oh its a great idea but not yet I would say. Of course publishing it would even better :)

**Comment by pavanramkumar** [comment]
Thanks for all your input. I think credit assignment is still unambiguous from commits and the way I write my job documents :) 

Also, I plan to submit pyglmnet to joss.theoj.org which provides a quick and painless peer review process with DOI. Ideally it will be published before the end of the year.

So I will make the transfer by tomorrow, Oct 21.

**Comment by pavanramkumar** [comment]
the move seems to have been largely successful! 

still need to work out exactly how to properly transfer:
- circle CI
- gitter channel

circle CI would be more urgent so that we can continue updating documentation seamlessly

**Comment by pavanramkumar** [comment]
figured out circle ci. i think this issue can now be closed.
