### ISSUE TITLE
Probable wrong gradient in linearized Poisson case

### ISSUE THREAD

**Issue by zhaoy271** [glm-tools/pyglmnet#181]
Hi,
I think the gradient (perhaps Hessian too) of linearized Poisson case is probably wrong in the cheatsheet. Eta in the second sum of gradient wrt beta_0 and beta_j should be exp(eta).

**Comment by pavanramkumar** [comment]
@zhaoy271 thanks for this! spotted the bug. Will patch soon

**Comment by jasmainak** [comment]
Merge if you're happy

**Comment by pavanramkumar** [comment]
@zhaoy271 bug is patched now, both in the docs and the code. thanks for your careful eye! let us know your experience and reach out for any other fixes.

**Comment by zhaoy271** [comment]
@pavanramkumar cool! I'm very interested in the linearized Poisson. Do you have any reference for it?

**Comment by pavanramkumar** [comment]
@zhaoy271 no refs because it's an in-house hack :) i've thought of it as a way to prevent the Poisson link and gradients from exploding in rare cases when `beta` is badly initialized.
