### ISSUE TITLE
Alternate distributions: Gamma Family

### ISSUE THREAD

**Issue by thenomemac** [glm-tools/pyglmnet#189]
Thoughts on integrating alternate loss distributions Gamma/Exponential. I know these losses aren't implemented in GLMNet but it could be a nice addition to differentiate this library. And I see no reason why they shouldn't work?

**Comment by pavanramkumar** [comment]
@thenomemac yes, we do have plans to add more exponential family likelihood / link functions. you're welcome to submit a pull request for gamma. we have an outline of what it would take to add a new distribution: http://glm-tools.github.io/pyglmnet/requests.html

**Comment by pavanramkumar** [comment]
@thenomemac see PR #213. We're looking for an illustrative example for Gamma GLMs. Do you have suggestions?

**Comment by thenomemac** [comment]
So Gamma would be used in Finance and Insurance for modeling things that
are "dollar" amounts since (as a general rule) long tail events cause
"amounts" to be heavily rightward skewed. Thus, gaussian loss will heavily
bias your predictions to a few outlier data elements. (think gamma is also
used in physics modeling?)

**Comment by jasmainak** [comment]
Thanks @thenomemac . After some thinking, maybe we can reproduce the plots in [this blog](http://seananderson.ca/2014/04/08/gamma-glms.html) since it doesn't need any data
