### ISSUE TITLE
fix group_lasso examples

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#202]

**Comment by Gibbsdavidl** [comment]
Using python 3.6 I get this error:

IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pyglmnet import GLM
   ...: from pyglmnet.datasets import fetch_group_lasso_datasets
   ...:

In [2]: df , group_idxs= fetch_group_lasso_datasets()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-310f4d9ff3ff> in <module>()
----> 1 df , group_idxs= fetch_group_lasso_datasets()

/usr/local/lib/python3.6/site-packages/pyglmnet/datasets.py in fetch_group_lasso_datasets()
    187         "http://genes.mit.edu/burgelab/maxent/ssdata/MEMset/train0_5_hs"
    188
--> 189     pos_file = tempfile.NamedTemporaryFile(bufsize=0)
    190     neg_file = tempfile.NamedTemporaryFile(bufsize=0)
    191

**Comment by RikUM** [comment]
fetch_group_lasso_datasets() doesn't work anymore. I think it has to do with the website; http://genes.mit.edu/burgelab/maxent/ssdata/MEMset/train0_5_hs

**Comment by jasmainak** [comment]
Please use the development version. A release is long overdue. I *just* need to find the time ...

**Comment by pavanramkumar** [comment]
closing since subsumed by more recent issues #267
