### ISSUE TITLE
Add pandas as dependency

### ISSUE THREAD

**Issue by brianhhu** [glm-tools/pyglmnet#227]
Currently the documentation only lists numpy and scipy as dependencies. I found that I also needed to install pandas (most likely for accessing the datasets), or the pip installation failed.

**Comment by jasmainak** [comment]
yes, this is a problem of mismatch between the `1.0` and `dev` version. Ideally, we should have a documentation for both. I'll try to see later today if it's easy enough to do

**Comment by jasmainak** [comment]
duplicate of #234
