### ISSUE TITLE
create model.predict_proba

### ISSUE THREAD

**Issue by hugoguh** [glm-tools/pyglmnet#23]
multinomial and binomial should output probabilities for each class. not just predicted class

**Comment by hugoguh** [comment]
it is actually always outputting probabilities
typically in sklearn `.predict` gives a class prediction and `.predict_proba` give probabilities. right now, .predict is always outputting probabilities which is fine. but just in case we want to make it similar to sklearn

**Comment by pavanramkumar** [comment]
implemented for `multinomial`. still need to do for `binomial` and a future implementation of `probit`
