### ISSUE TITLE
Update README and examples to reflect 1.0.1.dev0 version consistently

### ISSUE THREAD

**Issue by lv10** [glm-tools/pyglmnet#234]
Running [example](https://github.com/glm-tools/pyglmnet#getting-started) as follows produces an attribute error when calling simulate() in the following line:
`y_test = glm.simulate(beta0, beta, X_test)`

**Comment by jasmainak** [comment]
what version of pyglmnet are you using?

**Comment by pavanramkumar** [comment]
- Make sure README directs users to pip install the dev version
- Update examples to reflect dev version's API consistently
