### ISSUE TITLE
Probit is still not passing tests for cdfast solver

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#243]
May be related to over/underflow. See #224

**Comment by pavanramkumar** [comment]
To prevent overflow, use approximate gradient and hessian formulas. 
See Eq. 17-20 here: https://pdfs.semanticscholar.org/0c03/0537919f09575b9f2c0a98c62f6571bdceee.pdf

**Comment by jasmainak** [comment]
closed by #250
