### ISSUE TITLE
Installation command with python setup.py develop

### ISSUE THREAD

**Issue by cxrodgers** [glm-tools/pyglmnet#254]
The README says to install with this command:
  python setup.py develop install

But I have always used this:
  python setup.py develop

Source:  https://avolkov.github.io/installing-python-packages-in-development-mode.html

At least for me, the command in the README did not work -- I got "ImportError: No module named externals.six" -- but `python setup.py develop` did work. For what it is worth, I use python2 and conda to manage my installations, so this might change things.

Is there a reason to prefer `python setup.py develop install` in the README?

**Comment by jasmainak** [comment]
indeed @cxrodgers you are correct. Do you want to make a pull request to fix this.

ps: @pavanramkumar this is also probably the reason you were struggling with the installation the other day

**Comment by cxrodgers** [comment]
@jasmainak I created the PR. Note that the same instruction appears in the Makefile but I don't understand Makefiles so I didn't make any changes there.

**Comment by jasmainak** [comment]
closed by #255

**Comment by jasmainak** [comment]
Oops I merged too soon then :) But yeah I think the `Makefile` should be modified as well.
