### ISSUE TITLE
GLM parameter random_state ignored

### ISSUE THREAD

**Issue by geektoni** [glm-tools/pyglmnet#269]
I noticed that with `GLM` I cannot get consistent and replicable results even if I set the `random_state` parameter. Different run of the same code will produce always different results.

 I think that the problem can be found at this line: https://github.com/glm-tools/pyglmnet/blob/6763a9550fe87f1ab099db4f575a9e449e0b6a2d/pyglmnet/pyglmnet.py#L678
Since the `RandomState` object is never used to initialize randomly some of the parameters of the model, the `random_state` becomes useless.

**Comment by jasmainak** [comment]
indeed @geektoni do you want to help fix it with a pull request?

**Comment by geektoni** [comment]
Sure! #270 contains a proposed fix.

**Comment by jasmainak** [comment]
closed by #270
