### ISSUE TITLE
Wrong install instruction on the website.

### ISSUE THREAD

**Issue by geektoni** [glm-tools/pyglmnet#276]
The website of the project still contains wrong instructions to install the project "manually" directly from the `setup.py` file (see http://glm-tools.github.io/pyglmnet/install.html). I saw that it was already fixed in a previous PR (https://github.com/glm-tools/pyglmnet/pull/255/files), but it seems that the changes did not make it to the live version (I am reporting this because it happened to me to stumble upon this issue and it took me some time to figure out how to solve it).

**Comment by jasmainak** [comment]
@geektoni indeed. I was under the impression that we host the `0.1` documentation but it seems it shows the API of the dev version. So, we should just update it then.

(We don't host two versions because it's more work to build the documentation then ...)

**Comment by jasmainak** [comment]
Okay, it seems we have one example that breaks and one example that's stuck :\ We can't update the website before fixing these ...

**Comment by jasmainak** [comment]
closing this now as the release should have fixed it
