### ISSUE TITLE
ValueError: group should be (n_features,)

### ISSUE THREAD

**Issue by dduemig** [glm-tools/pyglmnet#291]
![image](https://user-images.githubusercontent.com/41909992/57326018-c0848500-710b-11e9-806f-975404b6632c.png)

I dont get this error

**Comment by jasmainak** [comment]
It doesn't happen for me. Can you provide a full script to reproduce instead of a screenshot. Here is what I tried:

```py
import numpy as np
from pyglmnet import GLM

group_ids = np.random.random(36)
X_train_trans = np.random.random((42603, 36))
y_train = np.random.random(42603)

glm = GLM(distr="gaussian", group=group_ids, alpha=0.05, reg_lambda=0.2, max_iter=1000)
glm.fit(X=X_train_trans, y=y_train)
```

**Comment by dduemig** [comment]
I found it

![image](https://user-images.githubusercontent.com/41909992/57401542-2a696100-71d6-11e9-9234-c0adc7e5a587.png)

now it works.

It is due to the datatype (np.float32 vs np.float64)

Could you fix that?

Thanks 

Best,
David

**Comment by jasmainak** [comment]
can you modify my script to show me how can I make it fail? It works for me whether I use np.float32 ro np.float64.

Yes, GridsearchCV used to work but I am not quite sure if it works on the latest version of sklearn.

**Comment by dduemig** [comment]
```
import numpy as np
from pyglmnet import GLM

group_ids = np.float32(np.random.random(36))
X_train_trans = np.random.random((42603, 36))
y_train = np.random.random(42603)

glm = GLM(distr="gaussian", group=np.float32(group_ids), alpha=0.05, reg_lambda=0.2, max_iter=1000)
glm.fit(X=np.float32(X_train_trans), y=np.float32(y_train))
```


But with the sklearn GirdsearchCV as well ? so not GLMCV ?

Can I use the package as grouplasso for penalizing betas of a cubic spline representation

**Comment by dduemig** [comment]
Is there already an open issue for the following 

![image](https://user-images.githubusercontent.com/41909992/57403870-efb5f780-71da-11e9-86c7-9043704bc08a.png)

Or am I doing something wrong ?

If I install pyglmnet I get version 1.0.0 
![image](https://user-images.githubusercontent.com/41909992/57403958-22f88680-71db-11e9-87ae-450fd3f63123.png)

**Comment by dduemig** [comment]
![image](https://user-images.githubusercontent.com/41909992/57404634-bc746800-71dc-11e9-8c0d-e985c8bfadfb.png)
![image](https://user-images.githubusercontent.com/41909992/57404647-c8602a00-71dc-11e9-886c-e8546cb530ee.png)

Does not seem to work ;(

**Comment by jasmainak** [comment]
You need to use the development version for this. Unfortunately we have a release due for a long time. Can you try using the development version in the meanwhile?

**Comment by jasmainak** [comment]
> But with the sklearn GirdsearchCV as well ? so not GLMCV ?

you can use both depending on your application.

> Can I use the package as grouplasso for penalizing betas of a cubic spline representation

sorry I don't know exactly what you are trying to do. But yes, we do support group lasso.

**Comment by dduemig** [comment]
Thank you for your answer.

I will try this tmr and let you know whether it works.

However, from the source code it seems that tscv (https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html) is not supported.

This would be super helpful for time series prediction tasks where k-fold etc. fail.

**Comment by jasmainak** [comment]
It would be nice for GLMCV to accept a cv object from sklearn but nothing stops you from using your own cv and using cross_val_score etc.

**Comment by dduemig** [comment]
Hey,

Is there a reason why it becomes so slow when I use the Github version?

![image](https://user-images.githubusercontent.com/41909992/57436072-3dfce200-723f-11e9-994f-3d81e65c39b9.png)


GridsearchCV seems to work 
![image](https://user-images.githubusercontent.com/41909992/57436770-b1ebba00-7240-11e9-95a0-7d6b4cbe7254.png)

But it is super slow ;( 

Any suggestions ? For my purpose its infeasible.

**Comment by jasmainak** [comment]
Just to be sure it's not a problem with the convergence criteria, can you set the max_iter lower and check the timings?

**Comment by pavanramkumar** [comment]
seems like the slowness is arising from the same root cause (group lasso). duplicated by #267
