### ISSUE TITLE
preparation for JOSS paper

### ISSUE THREAD

**Issue by jasmainak** [glm-tools/pyglmnet#297]
Hi everyone,

@pavanramkumar and myself have in the past discussed about writing a JOSS paper for pyglmnet.

JOSS articles generally provide a very high level description of the software and its relevance:

> Your submission should probably be somewhere between 250-1000 words.

It would allow us to properly point to pyglmnet in citations and get some scholarly recognition for our work. 

For this to reach fruition, we need to (checklist will be updated):
- [x] Fix the cdfast solver. Currently it is broken (cf https://github.com/glm-tools/pyglmnet/pull/278, https://github.com/glm-tools/pyglmnet/issues/289).
- [x] Make a new release and update the documentation.
- [x] Create a /paper directory in our repository where we prepare the submission. [see [author guidelines](https://joss.readthedocs.io/en/latest/submitting.html)]
- [x] Get a list of authors. I suggest being liberal -- that is anyone who contributed even one commit is invited to join the list as long as they are okay with it. Of course, it also implies [you will use Pyglmnet in your work](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)

cc @the872 @themantalope @daniel-acuna @marquesVF @tommyod @ravigarg27 @hugoguh @BeibinLi @peterfoley605 @geektoni @cxrodgers @evadyer 

and of course @koerding and @mshamalainen.

If you have any thoughts / objections, now is the time to voice them. Otherwise, we'll make this happen in the next couple of months.

**Comment by koerding** [comment]
Love the idea

**Comment by tommyod** [comment]
Great initiative, thanks for cc'ing me. :+1:  I can spare a few hours here and there over the next months, so if you want some help reviewing the software/docs/paper feel free to CC me on a PR/Issue. It's nice to work towards something concrete.

**Comment by geektoni** [comment]
Great idea! I will be glad to participate. Thanks for notifying me :+1:

**Comment by DreHar** [comment]
Fantastic; let me know if you need help with reviewing/editing

**Comment by jasmainak** [comment]
@DreHar would you mind looking at this PR: #313 ? Thanks a lot!
