### ISSUE TITLE
repository path is wrong on developer page

### ISSUE THREAD

**Issue by notuntoward** [glm-tools/pyglmnet#300]
Here:

http://glm-tools.github.io/pyglmnet/developers.html

the cloning command is given as

git clone https://github.com/user/pyglmnet

but it should be

git clone https://github.com/glm-tools/pyglmnet.git

**Comment by jasmainak** [comment]
well it doesn't matter if you clone from your fork or from upstream. I'm fine either way. What's important is that the remotes are set up correctly.

**Comment by jasmainak** [comment]
closed by #303
