### ISSUE TITLE
Need to install coverage

### ISSUE THREAD

**Issue by notuntoward** [glm-tools/pyglmnet#301]
On the developers page:

http://glm-tools.github.io/pyglmnet/developers.html

It might be worthwhile to mention that the coverage package is needed in order to run:

nosetests . --with-coverage

**Comment by jasmainak** [comment]
sure this would be a welcome change!

**Comment by notuntoward** [comment]
Even with `coverage `installed, nosetests don't run correctly.  Everything passes if I run:

`pytest .\tests\test_pyglmnet.py`

But if I try 

`nosetests . --with-coverage`

every function inside of test_pyglmnet.py which is decorated with:

`@pytest.mark.parametrize("distr", ALLOWED_DISTRS)`

fails.

It seems like the test functions have not actually been ported to nose.

**Comment by notuntoward** [comment]
Ah, I see.  The website documentation is out of sync with the code.  Would it be possible to update the website?

**Comment by jasmainak** [comment]
Yes, we need to make a release soon and that will bring it in sync. It's on my todo ...

**Comment by jasmainak** [comment]
closing this now as we have made a release now
