### ISSUE TITLE
Temporal functions

### ISSUE THREAD

**Issue by shainaraza** [glm-tools/pyglmnet#306]
I am curious about the temporal basis functions in yours code https://glm-tools.github.io/pyglmnet/auto_examples/plot_tikhonov.html

is it some source of timing context or is it during time-split cross validation.

**Comment by jasmainak** [comment]
I would say for timing context. @pavanramkumar can you confirm?

**Comment by shainaraza** [comment]
yes please confirm

**Comment by pavanramkumar** [comment]
@shainaraza thanks for your question. 

temporal basis functions are a frequently used technique in certain applications of GLMs to time series  
data to model the lagged effects of regressors on the target variable.
