### ISSUE TITLE
revisit convergence criteria

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#319]
current convergence criterion based on `norm(grad)` is not robust to dataset size. we need to make it a function of: 
- rate of change in loss, 
- `norm(grad)/norm(beta)` and 
- `n_features`

See e.g.: 
- https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html
- https://cran.r-project.org/web/packages/mize/vignettes/convergence.html

**Comment by jasmainak** [comment]
I think this is finished in #327
