### ISSUE TITLE
Adding how to cite the repo

### ISSUE THREAD

**Issue by titipata** [glm-tools/pyglmnet#360]
I think it would be better if we can add how to cite the repository (e.g. BibTeX) in both `README.md`, `README.rst` and `contributing.rst`. We can also do that after the JOSS submission since it needs a new DOI for the repository for JOSS submission.

**Comment by titipata** [comment]
@jasmainak, we can wrap this issue after you get a new Zenodo DOI's for the JOSS release.

**Comment by jasmainak** [comment]
yeah I am waiting for @pavanramkumar to update the zenodo and then will wrap up this issue!

**Comment by titipata** [comment]
Awesome, go @pavanramkumar!

**Comment by pavanramkumar** [comment]
you guys are awesome! i will update zenodo in next 24 hrs

**Comment by titipata** [comment]
🕤 🕥 🕦 🕧

**Comment by pavanramkumar** [comment]
new release created and DOI minted! zenodo page: https://zenodo.org/record/3679515#.XlHS1hdKhp8

@jasmainak if this satisfies the editor's criteria, you can update him on JOSS

**Comment by pavanramkumar** [comment]
@titipata i agree, let's update `README.rst` and `contributing.rst` after JOSS paper is published

**Comment by titipata** [comment]
@pavanramkumar, you might have to update the order of the authors so that it's aligned with `paper.md`

**Comment by titipata** [comment]
@pavanramkumar just poke here if you have time to update the order of authors in Zenodo. After updating the orders, @jasmainak can poke JOSS editor.

**Comment by jasmainak** [comment]
It's my bad actually, sorry I need to look at the PR with `.zenodo.json` ... it should have updated order.

**Comment by titipata** [comment]
Close this issue according to #373.
