### ISSUE TITLE
Convert matlab tutorial from Pillow's lab to pyglmnet

### ISSUE THREAD

**Issue by titipata** [glm-tools/pyglmnet#366]
Anyone would like to convert tutorial from https://github.com/pillowlab/GLMspiketraintutorial to `Pyglmnet`? It seems like audiences are partly from the neuroscience field. I think this will be super beneficial for them.

**Comment by jasmainak** [comment]
seems like there has already been a partial attempt: https://github.com/pillowlab/GLMspiketraintutorial/blob/master/python/tutorial1_PoissonGLM.ipynb.

It would be great to have more examples on public data that can demonstrate the use cases of pyglmnet.

**Comment by titipata** [comment]
Wow, that's awesome. I can take a look at it over the weekend. I'll see if it can be properly added to the Pyglmnet's tutorial.

**Comment by jasmainak** [comment]
that's great! might be a good idea to shoot the authors an email to ask permission to use the data. We can add the papers to cite in the example.

**Comment by titipata** [comment]
Ah yeah, they mentioned "**Data:** note that the dataset used for this tutorial is (unfortunately) not yet publicly available. If you would like access to the dataset needed to run the tutorial scripts, please write to pillow at princeton dot edu." Let me email him cc you to see if it is somehow possible or get relevance dataset.

**Comment by titipata** [comment]
@jasmainak what's the best way to create the tutorial and output? Adding a new file to `examples`?

**Comment by titipata** [comment]
I made PR #369 for this issue

**Comment by jasmainak** [comment]
yep add it to the examples directory :)

**Comment by titipata** [comment]
Close via #369
