### ISSUE TITLE
Visualize remaining training time when fitting a GLM object.

### ISSUE THREAD

**Issue by geektoni** [glm-tools/pyglmnet#379]
When training a model it would be beneficial to visualize some kind of progress bar to understand how much time it will take to complete all the iterations (at least if we do not converge).  

For instance, this feature could be easily added by wrapping a `range` object with `tqdm` (https://github.com/tqdm/tqdm). A flag could be then passed to the `GLM` object to enable/disable this feature. 

Any thoughts on this?

**Comment by jasmainak** [comment]
I think you might be able to achieve this using `logging` module or `print` commands?

**Comment by geektoni** [comment]
> I think you might be able to achieve this using `logging` module or `print` commands?

I'm not very familiar with the `logging` module, but I guess it depends on how much the users care about the "visual" experience. It would be possible to add just `print` statement all over the place, but I guess it wouldn't be a very elegant solution (too many `print` would kind of pollute the codebase).

**Comment by geektoni** [comment]
Add `tqdm` support in  #380.
