### ISSUE TITLE
full lambda path

### ISSUE THREAD

**Issue by linusheinz** [glm-tools/pyglmnet#381]
I probably just don't understand the difference compared to the R package. When I want to calculate the full lambda path instead of just one value of lambda, can I do that with one GLM call?

**Comment by jasmainak** [comment]
yes you can use [GLMCV](http://glm-tools.github.io/pyglmnet/api.html#pyglmnet.GLMCV) and provide a list of reg_lambda

**Comment by jasmainak** [comment]
closing as the solution provided seemed to have solved the issue for the OP or it was not of interest any more.

**Comment by linusheinz** [comment]
Solution was sufficient and worked well
