### ISSUE TITLE
code sparse version in the future

### ISSUE THREAD

**Issue by hugoguh** [glm-tools/pyglmnet#41]
blows up my memory, and sklearn doesn’t on the same dataset. 
Useful for problems with categorical features, number of features increases a lot with onehotencoder, but X will be sparse.

**Comment by jasmainak** [comment]
Memory profiling might be a good idea to see what's the culprit: http://fa.bianp.net/blog/2012/line-by-line-report-of-memory-usage/

**Comment by pavanramkumar** [comment]
duplicate of #229
