### ISSUE TITLE
PyPI packaging

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#43]
http://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/

**Comment by pavanramkumar** [comment]
I think it will be useful to consider the principles of semantic versioning for current and future releases: semver.org

**Comment by themantalope** [comment]
This still needs to be done, correct? I can set that up if needed.

**Comment by pavanramkumar** [comment]
Will let you know once docs are reorganized

**Comment by pavanramkumar** [comment]
I found some instructions: https://www.codementor.io/python/tutorial/host-your-python-package-using-github-on-pypi

I'll setup PyPI live and test accounts and let you know if you'd like to take over the rest.

**Comment by themantalope** [comment]
Sure. I've published before on PyPI before, so I figured I would volunteer!

**Comment by pavanramkumar** [comment]
hey @themantalope i've now done my bit to improve the tutorials and docs. you can feel free to go ahead with the PyPI process.

let me know once you're done and tested. we need to edit the README and docs to say that `pyglmnet` is pip installable!

**Comment by pavanramkumar** [comment]
let's follow the semantic versioning convention: http://semver.org/
according to this, the first release would be `0.0.0`.

**Comment by themantalope** [comment]
ok, I should be close. just working out the kinks with `twine`

**Comment by pavanramkumar** [comment]
according to this thread: http://stackoverflow.com/questions/3728626/what-to-use-as-an-initial-version

i feel like we should start at 1.0.0

**Comment by themantalope** [comment]
Ok, I'm setting up a PR that should bring everything needed into the master repo. Will also send you an email with some other instructions.

**Comment by jasmainak** [comment]
hmm ... I'm more used to starting with `0.1` in the python world ...
